### ISSUE TITLE
Logistic regression intercept scaling

### ISSUE THREAD

**Issue by vainius** [JohnLangford/vowpal_wabbit#1003]
If one of the classes was sampled in our training data we can get calibrated predictions by assigning weights to the observations.

However, we can also achieve that by scaling the intercept - multiplying it by the sampling rate.
In general, it gives different results from weighting and can be desirable in certain situations: when we want to predict one class better, but still have an average predicted class probability correspond to its occurrence in unsampled data.

We would like to add an option "--scale_intercept [float]" that would multiply the intercept by a given number after training, but before saving the model and scoring.

**Comment by JohnLangford** [comment]
If I understand correctly, this has the same effect as the 'base' in the
label.  https://github.com/JohnLangford/vowpal_wabbit/wiki/Input-format  so
having an option like "--default_base" would generalize this comment to all
regressors.  Maybe do that?  You can probably do it in scorer.cc very
easily.

-John

**Comment by JohnLangford** [comment]
Closing for now.

**Comment by ievag** [comment]
The base option adds the given constant to each prediction (even before the updates in the algorithm). This is not exactly what we were looking for. The idea of intercept scaling is to train the model on sampled data and to make the adjustment just on the final prediction.

**Comment by JohnLangford** [comment]
So, you do adjustment 0 while training and a nonzero adjustment for the
final prediction?

-John

**Comment by ievag** [comment]
Yes, that's what we need. In case of imbalanced data (e.g. where the positive examples in the data are very rare) one can take a sample where the proportion of positives is higher. Training a logistic regression on this sample results in higher final predictions. The intercept scaling allows to convert the probabilities so that these reflect the initial data before sampling.
Base option gives different coefficients and the interpretation of predictions is also different from that of an intercept scaling (base option could be used in a residual regression).
