### ISSUE TITLE
How can i get more than one result in prediction (not all) with --oaa <k>

### ISSUE THREAD

**Issue by root1984** [JohnLangford/vowpal_wabbit#1112]
How can i get more than one result after predict (not all) with --oaa <k>?

I need take 2 - 3 results is the most exactly. What parameter can do it?

With --probabilities param we just take all results with <k> label.

**Comment by arielf** [comment]
Have you tried to follow [this wiki?](https://github.com/JohnLangford/vowpal_wabbit/wiki/One-Against-All-(oaa)-multi-class-example)

Otherwise, or if things don't work as expected, can you please provide a reproducible example of the problem you're having?

1. data-file
2. exact command line used
3. expected result description vs 
4. actual result

**Comment by JohnLangford** [comment]
Are you looking for --multilabel_oaa ?
