### ISSUE TITLE
libboost_program_option isn't found on Ubuntu 14.04

### ISSUE THREAD

**Issue by alexott** [JohnLangford/vowpal_wabbit#1167]
On Ubuntu 14.04, the libboost_* libraries are installed in the `/usr/lib/x86_64-linux-gnu`, not in the `/usr/lib`, or `/usr/lib64`

By modifying the variable `libsubdirs` in the `acinclude.d/ax_boost_base.m4` to include `lib/x86_64-linux-gnu` fixed this issue, but it should be more generic.

**Comment by arielf** [comment]
It is unclear what the problem is and how you got into a state of problem.

Ubuntu/Debian doesn't require messing up with options or flags.  `vw` should build smoothly without needing to change anything in any config files (let alone auto-generated ones).

The `Makefile` in the source tree has the correct:

     ifeq ($(UNAME), Linux)
           BOOST_LIBRARY += -L /usr/lib/x86_64-linux-gnu

even though it is not strictly needed, as this dir is already included in the system default. See: `/etc/ld.so.conf.d/x86_64-linux-gnu.conf`.

On Ubuntu/Debian you shouldn't be using `autogen.sh` (not sure you did, but that's a possibility). It overwrites `Makefile` and is not recommended.

Just follow the [official instructions](https://github.com/JohnLangford/vowpal_wabbit/blob/master/README.md) of building on Ubuntu, reproduced here for your convenience:

    # -- Get libboost program-options and zlib:
    apt-get install libboost-program-options-dev zlib1g-dev

    # -- Get the python libboost bindings (python subdir) - optional:
    apt-get install libboost-python-dev

    # -- Get the vw source:
    git clone git://github.com/JohnLangford/vowpal_wabbit.git

    # -- Build:
    cd vowpal_wabbit
    make
    make test       # (optional)
    make install

IOW:
Unless you have a messed up system (non-standard LD_LIBRARY_PATH and/or ldconfig, non original Makefiles, etc.) `vw` should build out of the box on Ubuntu (any reasonably recent version) and find libboost_* in the correct place.

**Comment by alexott** [comment]
Ok, sorry for noise - I removed the old git clone, re-did the fresh clone & now it's detected correctly...
