### ISSUE TITLE
auditing the regressor in an error correcting tournament

### ISSUE THREAD

**Issue by ekg** [JohnLangford/vowpal_wabbit#1195]
How should we interpret the --audit_regressor results in the case of an error correcting tournament? Is it possible to do so?

**Comment by JohnLangford** [comment]
It's difficult to interpret because the mapping from regressor to node in the ECT is defined by the ECT and not apparent in the audit results.  To really get at this, you should edit the ECT code to print additional information as it descends or ascends the data structure for prediction or learning.

**Comment by JohnLangford** [comment]
(Closing for now, reopen if needed.)
