### ISSUE TITLE
Multiple models during prediction and performance

### ISSUE THREAD

**Issue by tilayealemu** [JohnLangford/vowpal_wabbit#1207]
Thanks for VW. It's very helpful. I'm planning to use it in an environment with tens of thousands of models. I can afford to take a bit of time to train the models but speed is crucial during prediction. [This](https://github.com/JohnLangford/vowpal_wabbit/wiki/Daemon-example) daemon example cites excellent performance results. However, does the daemon support hosting multiple models (not just a few but thousands)?

Alternatively, is there a way of loading VW models onto memory so that they can be cached and be repeatedly used for prediction? This would be ideal because users can then choose their own framework for wrapping those models inside a service, load balancing the service, and so on.

Appreciate all suggestions.

**Comment by arielf** [comment]
Answers and tips:
- No: each `vw` process can only support a single model
- Yes, model is mapped into memory
- `-c` (caching) helps only for repeating identical data (e.g multiple passes on the same train set) it doesn't help in train vs predict (new examples).
- You must "train as you test/predict": exactly same names+types of features in both.
- Your performance will most likely be limited by on-the-fly feature extraction/generation, not by `vw` itself
- A context switch between the vw process and the feature-generation feeder can cause significant performance degradation. Pipelining: sending N-examples at a time rather than one a time (writing example then reading prediction) would greatly improve throughput.
- Need for thousands of models. Tip: you can trivially have "1000 submodles" in one file by using a `vw` name-space to separate the examples into sets, with a higher `-b <bits>` value to minimize hash-collisions.
- If you run separate models on the same machine, you would also need to make them listen on separate ports.  Consider that you might run out of ports in this case.

Here's a brief data-set example implementing multiple sub-models in one file, using name-spaces:
```
1 ex1_1 |model1 features...
1 ex2_1 |model2 features...
-1 ex2_2 |model2 features...
-1 ex1_2 |model1 features
...
1 exN_1 |modelN features...
```

**Comment by tilayealemu** [comment]
Thanks Ariel.

The submodel example is interesting. Didn't see it in the docs before. My requirements are to separate the models though - to keep model size small, to be able to re-train individual models when needed, and to do parallel training.

Agree, running a daemon per model has several monitoring and performance consequences.

Regarding loading models to memory, I found [this](https://github.com/JohnLangford/vowpal_wabbit/blob/master/java/src/test/java/vowpalWabbit/learner/VWMulticlassLearnerTest.java#L43) unit test,
```
        vw = VWLearners.create("--quiet -t -i " + cbModel);
        String[] test = new String[]{
            "1:2 3:5 4:1:0.6 | a c d",
            "1:0.5 2:1:0.4 3:2 4:1.5 | c d"
        };

        int[] testPreds = new int[test.length];
        for (int i=0; i<testPreds.length; ++i) {
            testPreds[i] = vw.predict(test[i]);
        }
        int[] expectedTestPreds = new int[]{4, 4};
        vw.close();
```

Would caching the `vw` variable do the trick?

**Comment by tilayealemu** [comment]
Closing ticket. Will go with caching the models. Example class below if others are interested.

```
import vowpalWabbit.learner.VWLearners;
import vowpalWabbit.learner.VWMulticlassLearner;

import java.io.File;
import java.io.IOException;
import java.util.Arrays;

public class TestReuseModel {

    public static void main(String[] args) throws IOException {

        System.load(new File(".").getCanonicalPath() + "/target/vw_jni.lib");

        // actions: 1=warm, 0=cold, first 4 examples have good reward, last 4 have bad rewards
        String[] train = new String[]{
                "1:-1.0:0.5 'ex1_summer | season_summer sun",
                "1:-0.9:0.5 'ex2_summer | season_summer cloud",
                "2:-0.9:0.5 'ex3_winter | season_winter sun",
                "2:-1.0:0.5 'ex4_winter | season_winter cloud",
                "2:0.0:0.5 'ex5_summer | season_summer sun",
                "2:-0.1:0.5 'ex6_summer | season_summer cloud",
                "1:-0.1:0.5 'ex7_winter | season_winter sun",
                "1:0.0:0.5 'ex8_winter | season_winter cloud"
        };
        String cbModel = new File("vw.model").getAbsolutePath();

        VWMulticlassLearner vw = VWLearners.create("--quiet --cb 2 -f " + cbModel);
        int[] trainPreds = new int[train.length];
        for (int i = 0; i < train.length; ++i) {
            trainPreds[i] = vw.learn(train[i]);
        }
        vw.close();

        vw = VWLearners.create("--quiet -t -i " + cbModel);
        String[] test = new String[]{
                "'summer_sun | season_summer sun",
                "'winter | season_winter",
                "'winter_cloud | season_winter cloud",
                "'sun | sun",
                "'cloud | cloud"
        };

        int[] testPreds = new int[test.length];
        for (int i = 0; i < testPreds.length; ++i) {
            testPreds[i] = vw.predict(test[i]);
        }
        vw.close();

        System.out.println(Arrays.toString(testPreds));
    }
}
```
