### ISSUE TITLE
Using vw varinfo on Windows

### ISSUE THREAD

**Issue by grigoriysol** [JohnLangford/vowpal_wabbit#1221]
Hello!
I want to use varinfo on Windows.
As I understand it is a perl-script.
I installed a perl.
perl and vw registered in PATH Windows

running varinfo on cmd via perl

> C:\>perl "C:\Vowpal Wabbit\utl\vw-varinfo" "C:\Vowpal Wabbit\utl\train.vw"
> 
> Error: option '--data' cannot be specified more than once
> vw (d:\a\1\s\vowpalwabbit\io_buf.h:123): can't open: C:\Vowpal.writing, errno =
> Permission denied
> Error: can't open: C:\Vowpal, errno = No such file or directory
> vw (d:\a\1\s\vowpalwabbit\io_buf.h:123): can't open: C:\Vowpal, errno = No such
> file or directory
> FeatureName        HashVal   MinVal   MaxVal    Weight   RelScore
> 

What is the reason?
It does not work on Windows? Only under Unix?
Maybe there is an analog for Python?

**Comment by arielf** [comment]
Sorry for not being able to help much here.  Nevertheless, a few tips that may help:

- Your assumption is correct. I wrote `vw-varinfo` and I never tested it in Windows or claimed it works on Windows.
- The specific issues of `permission denied` and 'can't open`_may_ be solved by using directory names without spaces.  `C:\Vowpal Wabbit` has a space it, and is being confused as two separate args, the 1st being `C:\Vowpal`.  However, fixing this may very likely just lead to the next issue. 
- The safest/guaranteed way to run code like this "on windows" is to use a VM, like virtualBox with Ubuntu or Debian in it.
- There's a newer, better, faster version of vw-varinfo called `vw-varinfo2`, written in python, but it doesn't yet support multi-class which is why I haven't merged it back in.  Disclaimer: It was also only tested on Linux. Feel free to try it if it fits your case.  [Link to vw-varinfo2](https://github.com/arielf/weight-loss/blob/master/vw-varinfo2)

As always, patches (aka pull requests) to make existing code run on Windows are always welcome from Windows users.

**Comment by grigoriysol** [comment]
Thank you! @arielf 
Yes indeed. Removed the space and perl script in path "C:\Vowpal Wabbit" (chang to "C:\Vowpal_Wabbit") ! Now we need to figure out what it shows!))

Script on the python on windows did not work, swear at the Path, although with him everything is fine.

PS C:\> python "F:\GitHub\weight-loss\vw-varinfo2" "C:\Vowpal_Wabbit\utl\train.vw"
== FATAL: Sorry: can't find vw (vowpal wabbit
PATH=%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\VowpalWabbit;C:\Program Files (x86)\Python35-32\Scripts\;

**Comment by arielf** [comment]
Thanks for the report.  Such reports make it easier for non WIndows user to support Windows.

I believe I have a fix for this but I don't use Windows so can't test well.

In my fix, I am assuming that  `C:\Program Files\VowpalWabbit` (or anything else you may have in your PATH) possibly has a file called `vw.exe` (rather than `vw`) in it.

I just pushed the fix to github.  Try to download the latest version of `vw-varinfo2`

**Comment by grigoriysol** [comment]
I downloaded the latest version.
Unfortunately, this did not help. The error is the same as it was

**Comment by arielf** [comment]
Actually, it is not the same as it was :)
I see you have a wrong setting in your PATH.
In now includes: `C:\Program Files\VowpalWabbit\vw.exe` (which is not a directory)
But I also see the directory `C:\Program Files\VowpalWabbit` is already there earlier in the list, which if correct should allow finding `vw.exe` there.  Is `vw.exe` there and is it executable?

You could debug this by placing some `print("fpath: %s: %s" % (fpath, 'Yes!' if os.path.exists(fpath) else 'No')` call inside the `is_exe` function etc.

Sadly I don't have your env to reproduce and nail the problem.

A work around, BTW: is to pass the actual `vw` program as the 1st argument to `vw-varinfo2` and to comment out all the `if which(vw_exe) is None` section (3 lines).
HTH

**Comment by grigoriysol** [comment]
Yes I know 
I added this path "C:\Program Files\VowpalWabbit\vw.exe" for a simple check - usually so no one does.

Thanks a lot for your help.
This is more than enough.
If I can understand your code, I will obligatorily send it to you.

Small question:
How to use knowledge about weights in the varinfo? I could not find the detailed instructions and would.

This is clearly not enough:
https://github.com/JohnLangford/vowpal_wabbit/wiki/using-vw-varinfo

For example, if I have a Weight or RelScore negative.
1. I exclude these functions from the model (for example, through -feature_mask arg)
2. Or vw simply does not take them into account in predictions.

**Comment by grigoriysol** [comment]
Thanks for the help.
The question of interpreting the model will be studied further

**Comment by arielf** [comment]
A negative weight means a feature that inversely correlated with the label. It is important in the sense that it affects the target/label.

Features that are not important, their weights are near zero.

Excluding negative features? I can't see a reason for this. It will hurt the model.

_"How do I use the knowledge about weights"?_

I'm not sure I understand the question. Let me try:

All that `vw-varinfo` (and `vw-varinfo2`) does is give you a summary of the features included in the model and their relative importance (effect on the target, aka 'label').  No more and no less.

Does this answer your questions?

**Comment by grigoriysol** [comment]
Yes thank you!
This is more than I expected!
