### ISSUE TITLE
More consistently git tagging versions?

### ISSUE THREAD

**Issue by Refefer** [JohnLangford/vowpal_wabbit#1264]
Hi there,

We typically compile from source as part of our deployments, and recently we've noticed that the vw repo isn't tagging versions when version bumps happen.  This is especially problematic as the python bindings reject anything not directly tied to that vw version, resulting in random errors.

Can we start tagging and pinning all releases?  It's small effort but dramatically simplifies reliable builds, debugging, code sharing, etc.

**Comment by JohnLangford** [comment]
Let's get the meaning straight.  There are releases, tags, and versions.  

I've generally thought of all releases as being here: https://github.com/JohnLangford/vowpal_wabbit/tags which means they are by definition tagged.  Versions iterate the minor number as well (so it's currently 8.3.3), but I generally don't think of a minor bump as as a 'release' and have not tagged it. 

I gather that you are thinking of the minor bumps as also a release?  I'm not entirely comfortable with that as significantly more testing goes into an 8.x release rather than an 8.3.x bump.  The minor bumps have primarily been used to help keep track of possibly-forwards-incompatible changes.

**Comment by JohnLangford** [comment]
Closing for now, but reopen if you have a specific proposal.
