### ISSUE TITLE
Windows MSI Install - vw-varinfo not found

### ISSUE THREAD

**Issue by balajisr8** [JohnLangford/vowpal_wabbit#1284]
Hi,

I have installed Vowpal Wabbit using MSI Installer for windows from url https://github.com/eisber/vowpal_wabbit/releases V8.3.0.9. vw works fine but I am not able to get variable importance for the model using vw-varinfo.

Please help.

Regards
Balaji SR

**Comment by JohnLangford** [comment]
vw-varinfo is a script---I would not expect it to work on the windows side unless you have installed unix support.  @arielf may know more.

**Comment by arielf** [comment]
Correct.  `vw-varinfo` is a perl-script written and tested on Ubuntu.

Generally, perl scripts should be able to run in any env, however command locations and paths may be different.  Patches to make it work on Windows from people who run Windows are welcome.

Most of the reports I've seen in the past on WIndows were due to incorrect/unset `PATH` variable (I think it is  `%PATH%` on WIndows), so `vw-varinfo` can't find `vw` (and possibly other standard utilities)

If this is the problem in this case, it shouldn't be too hard to make it work.

To be helpful, a problem report should include an exact command tried and its output (the error message).

**Comment by arielf** [comment]
Oops. rereading this I just realized that the problem is not in running `vw-varinfo` but in installing it (I think).

If so you may get `vw-varinfo` from the source tree itself. It is under the `utl` directory:
    https://github.com/JohnLangford/vowpal_wabbit/tree/master/utl

There's also a better/faster/simpler/newer implementation in python but with no support for multi-class here:
   https://raw.githubusercontent.com/arielf/weight-loss/master/vw-varinfo2
