### ISSUE TITLE
oaa parallel training and predictions of underlying models

### ISSUE THREAD

**Issue by Wirack** [JohnLangford/vowpal_wabbit#1351]
I have been examining how to make oaa faster and would appreciate your feedback regarding the feasibility of the following approach.

Perhaps it would make sense to parallelise training and predictions of the underlying binary models of oaa per example.
Do you think it would be worthwhile to invest some energy in implementing parallel training and prediction for oaa in terms of performance gain?

I noticed the following [code](https://github.com/JohnLangford/vowpal_wabbit/blob/7c1c63f6e33812736c79bcfa90547ea50c3bd586/vowpalwabbit/learner.h#L119-L121). It appears that the offset is passed via the example struct. Could it be changed to be a variable to the learning and prediction functions instead, as to make the parallelisation implementation cleaner (avoid state)?

**Comment by JohnLangford** [comment]
The obvious thing to look at is the multipredict interface here:
https://github.com/JohnLangford/vowpal_wabbit/blob/7c1c63f6e33812736c79bcfa90547ea50c3bd586/vowpalwabbit/learner.h#L128

Hal Daume @hal3 did some initial work on a multilearn interface as well,
but I think he ended up frustrated.  There were two issues I recall:
1) It's obviously a bit more complex than multipredict.
2) It's not as big a win because the updates are sparse by default given
this line:
https://github.com/JohnLangford/vowpal_wabbit/blob/7c1c63f6e33812736c79bcfa90547ea50c3bd586/vowpalwabbit/gd.cc#L566
guards the update rule.

With the above said, I don't think an effect multilearn has been ruled
out.  Perhaps Hal can comment further?

W.r.t. interfaces, there is a very good reason that the offset is handled
mechanically by the class.  Empirically difficult-to-debug work cropped up
everywhere since the indexing became prohibitively complex without the code
you pointed out.  The key thing is that you need to _undo_ changes to the
offset.  There may be a way to do this as a parameter rather than an
example field, but an approach which avoids inducing bugginess in the
common case (i.e. not multilearn) is a must.

-John

**Comment by Wirack** [comment]
Thanks for the reply. That gives me some pointers if I am to implement such functionality.

**Comment by JohnLangford** [comment]
Closing for now.  A patch is welcome.
