### ISSUE TITLE
Installation failed Windows

### ISSUE THREAD

**Issue by tigeredo** [JohnLangford/vowpal_wabbit#1374]
Hello,

I'm trying to install vw using pip and I'm getting a [WinError 2] : The system cannot find the file specified.
I've tried to clone the repos and using python setup.py install, also getting same error. I've run cmd as admin, also the same.

Does anyone know how to fix this ? Thanks !

**Comment by spinkney** [comment]
Instead of using pip, try the .msi installer located at https://github.com/eisber/vowpal_wabbit/releases

**Comment by tigeredo** [comment]
Would I be able to use it in python ?

**Comment by MLWave** [comment]
> Would I be able to use it in python ?

No. The .msi installer just has the executable.

**Comment by JohnLangford** [comment]
@Scott-Graham-Bose any thoughts on this?

**Comment by Scott-Graham-Bose** [comment]
sorry, i don't know anything about the windows side =(

**Comment by JohnLangford** [comment]
Maybe @eisber has an idea?

**Comment by eisber** [comment]
The .msi doesn't have the python .dll either. Needs to be custom built.

**Comment by sharatsc** [comment]
The problem is that python setup.py is looking for zlib.dll file that is currently not provided by the zlib.v140.windesktop.msvcstl.static.rt-dyn nuget package. if we use zlib.greedy(https://www.nuget.org/packages/zlib.greedy/) package instead, the dynamic libraries are made available. I was able to do python setup.py build and python setup.py install after copying the zlib.dll into python/bin folder.

**Comment by JohnLangford** [comment]
Thanks @sharatsc  It sounds like you have a reasonable solution.
