### ISSUE TITLE
Contextual Bandit Bag implementation doesn't return actions ordered by underlying scores

### ISSUE THREAD

**Issue by eisber** [JohnLangford/vowpal_wabbit#1470]
Epsilon greedy sorts actions by model scores, bag does not

**Comment by JohnLangford** [comment]
@matanster, I suspect @eisber is just referring to the order of the actions in the created distribution.

@eisber, this is a pretty subtle thing.  It seems unlikely that the best policy is to sort by the model score because the probability of winning in a bag is more fundamental thing.  In particular, we should not consider an action particularly "good" if it wins one outcome by a mile and loses all the others by a little bit---this is just evidence of instability in our update rule.  

Instead, it seems likely that we just wish to break ties according to the underlying score.

**Comment by JohnLangford** [comment]
@matanster, I suspect @eisber is just referring to the order of the actions in the created distribution.

@eisber, this is a pretty subtle thing.  It seems unlikely that the best policy is to sort by the model score because the probability of winning in a bag is more fundamental thing.  In particular, we should not consider an action particularly "good" if it wins one outcome by a mile and loses all the others by a little bit---this is just evidence of instability in our update rule.  

Instead, it seems likely that we just wish to break ties according to the underlying score.  I did this in #1505 for the adf code.
