### ISSUE TITLE
-b larger than 32 and -f for 2 non-zero weights: training is fast, model writing extremely slow

### ISSUE THREAD

**Issue by eisber** [JohnLangford/vowpal_wabbit#1474]
When adding "-f model" vw allocates >100GB, but doesn't finish within multiple minutes.
In contrast training without model writing, just finishes within seconds.

Command:
vw -d regression_data_3.txt -f model  -b 33

Input data: 

1 |a 0:1 |b 2:2
0 |a 0:1 |b 2:4

**Comment by JohnLangford** [comment]
This is expected behavior.  Saving a model requires iterating through a large array checking if each entry is nonzero.  This causes the OS to instantiate the array leading to running out of RAM.  If you want to use a large number of bits, you should use --sparse_weights which makes training an order of magnitude slower but never allocates memory for unused weights.
