### ISSUE TITLE
Installation on CentOS 6

### ISSUE THREAD

**Issue by matanster** [JohnLangford/vowpal_wabbit#1496]
Just for the record, on CentOS 6.9 and possibly all CentOs 6, you currently have to upgrade g++ to a version supporting c++ 11, as the default g++ there does not support c++ 11. If you get a myriad of compilation errors, that's likely the underlying cause.

1. I could perform the upgrade by following here: https://hiltmon.com/blog/2015/08/09/c-plus-plus-11-on-centos-6-dot-6/. I then built boost from source, following [here](https://gist.github.com/1duo/2d1d851f76f8297be264b52c1f31a2ab) while adding the option --with-program_options. So that it builds with the same compiler version that VW will be building with... and includes program_options in its build, which is otherwise skipped.
2. Then I copied boost's header files directory to where g++ would find them (/usr/local/include), as I didn't want to fiddle VW's build files for that. I then also made g++ find boost's `program_options` module by adding `/opt/boost/lib/` to the LIBRARY_PATH environment variable.
3. Adding `/opt/boost/lib/` to the LD_LIBRARY_PATH environment variable as well, so that Java can also find it, for the Java build enabling using VW from Java.

Apart from the last hackish step, I guess these are the missing installation pieces for CentOs 6. I should make an installation guide next time around, sans the hackish steps that can surely be replaced by nicer ways of telling g++ where to find boost, e.g. making the initial boost build drop its artefacts in places already searched for headers and modules.

**Comment by matanster** [comment]
That said, at runtime I run into:
> java.lang.UnsatisfiedLinkError: no vw_jni in java.library.path

The same error was heavily discussed in the [docker related issue](https://github.com/JohnLangford/vowpal_wabbit/issues/894), and underlying mechanics were improved in the epic PR that eminated. Any quick idea as to what might be the trouble with the current VW master, causing this on a CentOS machine?

**Comment by matanster** [comment]
My issue, was [not specific to CentOs](https://github.com/JohnLangford/vowpal_wabbit/issues/1148#issuecomment-396871582).  Solved.

**Comment by arielf** [comment]
I realized that this issue is closed, but just for reference in case someone hits this page.

Building the java runtime support for `vw` is pretty simple on Linux (I use Ubuntu, trying to avoid other distros because of convenience and ease of management, I find it much smoother than CentOS due to the very large number of prebuilt "just works" packages)

First, yes, you need an env var setting for JAVA_HOME, mine is:
```
$ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
```

And building the `vw_jni.so`, once this var is set in the environment, is straight-forward too.
See [this Stackoverflow answer](https://stackoverflow.com/questions/48669098/vowpal-wabbit-with-java-jni-using-the-linux-precompiled-binaries)

And this [specific comment on how to get java vw support on Ubuntu in 3 simple steps](https://github.com/JohnLangford/vowpal_wabbit/issues/1305#issuecomment-320479104)

Just thought I should add this info, just in case it helps anyone in the future.
