### ISSUE TITLE
Contextual Bandit (DM): not predicting correctly when only one action is allowed

### ISSUE THREAD

**Issue by raphaelberly** [JohnLangford/vowpal_wabbit#1516]
There seem to be an issue with the current version of master, using Contextual Bandit of type DM, when only one action is allowed to be predicted.

To convince myself that there was an issue, I used the following very simple toy example.

### The toy example

My file `train.txt` contains the following data:

```
1:10:0.5 | a
2:-10:0.5 | a
3:0:0.5 | a
1:-10:0.5 | b
2:10:0.5 | b
3:0:0.5 | b
```
There are thus 2 features and 3 possible actions. I train the model using the command: `vw --cb 3 --cb_type dm -f cb.model -d train.txt`

The `predict.txt` data contains the following data:

```
1 | a
2 | b
3 | c
1 | a b
2 | b c
3 | a c
```
The output should thus be `1 2 3 1 2 3`. I predict using the command: `vw -t -d predict.txt -i cb.model -p output.txt`

However, the observed output is the following:
```
2
1
2
2
1
2
```

### Question

I believe this is not normal, do you have any idea what could lead to this?

**Comment by JohnLangford** [comment]
I can't reproduce---I get:
$ cat output.txt 
1
2
3
1
2
3

**Comment by MLWave** [comment]
Can't reproduce with 8.1.1 on Mac.

**Comment by quentin-auge-pretty** [comment]
Well, I can reproduce it using the following script.

```bash
#!/usr/bin/env bash

git clone https://github.com/JohnLangford/vowpal_wabbit.git
cd vowpal_wabbit
make -j4

cat > train.txt <<EOF
1:10:0.5 | a
2:-10:0.5 | a
3:0:0.5 | a
1:-10:0.5 | b
2:10:0.5 | b
3:0:0.5 | b
EOF

./vowpalwabbit/vw --cb 3 --cb_type dm -f cb.model -d train.txt

cat > predict.txt <<EOF
1 | a
2 | b
3 | c
1 | a b
2 | b c
3 | a c
EOF

./vowpalwabbit/vw -t -d predict.txt -i cb.model -p output.txt

cat output.txt
```

Head commit is ae732d5ceb5dc18c294d80582dd6e5e3774e0b03.

Output:

```
2
1
2
2
1
2
```

**Comment by JohnLangford** [comment]
I can reproduce with the script, thanks.

Looking at the invert_hash file via: 
./vowpalwabbit/vw --cb 3 --cb_type dm -f cb.model -d train.txt --invert_hash readable.model

You see:
Constant:202096:0.128491
Constant[1]:202097:-0.128491
a:108232:0.475706
a[1]:108233:-0.475706
b:129036:-0.480024
b[1]:129037:0.480024

So, in the first example '2' is preferred (a[1] < a) and in the second example '1' is preferred (b < b[1]).  For the 3rd example, there is no 'c' feature so it's an implicit zero.  Hence, '2' is preferred since Constant[1] < Constant.  For the 4th example, Constant[1]+a[1]+b[1] < Constant+a+b, so action 2 is preferred.  The 5th and 6th examples are just like examples 2 and 1 since c-related parameters are implicit 0.

**Comment by raphaelberly** [comment]
Thanks for your answer. 

I agree with your interpretation of the model. However, I specified in `predict.txt` the "list of available actions", and this list contains only one value. So I was expecting to get this value as output prediction.

Shouldn't the expected behaviour be that the model necessarily returns the only specified action as the output?

Moreover, this used to be different. Using 8.5.0 and some older versions, I get what I expect on my toy example, i.e. `1 2 3 1 2 3`.

**Comment by JohnLangford** [comment]
This is explains why I couldn't reproduce---I was using an older version of VW.

The critical bit of code is here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gen_cs_example.h#L60  Basically, if there is either 0 or 1 actions, it assumes that you are supposed to choose amongst all, and otherwise it assumes that you should choose amongst the subset.  

The question is: How should the 1-action case be handled?  If it's a CB label, we definitely want to do an update, which may touch every action.  If it's just an action specification...  alright, see #1521 .

**Comment by quentin-auge-pretty** [comment]
Works like a charm, thanks!

$ cat output.txt
1
2
3
1
2
3
