### ISSUE TITLE
cb-adf always generates the same predictions

### ISSUE THREAD

**Issue by TingtingGu** [JohnLangford/vowpal_wabbit#1523]
Hi,

I am investigating using ADF to select different ads. I am trying with a sample

suppose:
a_1: Action 1: Hamburg
a_2: Action 2: Vegburg
a_3: Action 3: Salad

I am expecting when seeing feature 'lessHealthy', a_2 or a_1 would be the best action. when seeing feature 'Healthy', a_3 would be best action.

My training set is like: (vw -d cb_adf.train -f cb_adf.m)

cb_adf.train:

shared | lessHealthy
| a_1
0:-10:0.3 | a_2
| a_3

shared | Healthy
| a_1
| a_2
0:-10:0.3 | a_3

Then I use the model to do predictions (vw -t -i cb_adf.m cb_adf.test -p cb_adf.predict)
cb_adf.test is like

shared | lessHealthy
| a_1
| a_2
| a_3

shared | Healthy
| a_1
| a_2
| a_3

I get '1' for both of them.

Can any one explain what's happening? Any hints would be appreciated.

**Comment by JohnLangford** [comment]
You need to interact the shared and action-specific features (via -q) for the shared features to influence the ranking.

**Comment by matanster** [comment]
Should I add that in the Wiki section discussing shared features and ADF? seems to be somewhat of a recurring question.

**Comment by matanster** [comment]
On the same topic, if we emulate non-ADF in ADF (say for using some VW feature that's not available with non-ADF, or as part of a soft transition to ADF), should we in theory get the same performance training an offline policy, as we would with our pre-ADF?

```
def to_vw_entry(row):
  acp = str(row['vw_action_number']) + ":" + str(row['model_cost']) + ":" + str(row['action_prob']) # the Action:Cost:Probability format of VW 
  
  numeric_context_features = " ".join(list(map(functools.partial(to_vw_numeric, row=row), numeric_features)))
  categorical_context_features = " ".join(list(map(functools.partial(to_vw_categorical, row=row), categorical_features)))
  
  return acp + " | " + numeric_context_features + " " + categorical_context_features + '\n'


def to_vw_adf_entry(row):
    
    numeric_context_features = " ".join(list(map(functools.partial(to_vw_numeric, row=row), numeric_features)))
    categorical_context_features = " ".join(list(map(functools.partial(to_vw_categorical, row=row), categorical_features)))
    
    vw_adf_entry = 'shared |s ' + numeric_context_features + " " + categorical_context_features + '\n'
    
    for action in action_numbers:
        
        if action == row['vw_action_number']:
            acp = str(row['vw_action_number']) + ":" + str(row['model_cost']) + ":" + str(row['action_prob']) # the Action:Cost:Probability format
            vw_adf_entry += acp + ' |d dummy' + str(action)
        else:
            vw_adf_entry += ' |d dummy' + str(action)
            
        vw_adf_entry += '\n'
    
    vw_adf_entry += '\n' # indicating end of entry
    
    return vw_adf_entry
```

This code piece is pulling values from pandas DataFrames, that's why the square brackets with attribute names, but you can substitute that for anything else without activating a brain cell. 

Disclaimer: this code doesn't encode features _other than_ shared features, as I used it to test an ADF flag for a non-ADF scenario. But it's easy to add. Also it's only my interpretation of the format though I've taken diligence to validate it as much I could.
