### ISSUE TITLE
--oaa option appears to be broken

### ISSUE THREAD

**Issue by ma2rten** [JohnLangford/vowpal_wabbit#493]
I ran vowpal wabbit with the following options:

    vw --loss_function logistic --oaa 121 -d train.vw -f model
    vw --loss_function logistic --oaa 121 -i model -t -d test.vw -r raw_predictions.txt

I am getting the following error

    only testing
    vw: option '--oaa' cannot be specified more than once

when I leave out the option ```--oaa 121```

I get 

    You are using a label not -1 or 1 with a loss function expecting that!

**Comment by ma2rten** [comment]
I tried it on master as well as on older versions of vw. I seems like the oaa option has been broken for quite a while.

**Comment by arielf** [comment]
Hi,

`--oaa` is a multi-class option: labels should be integers in the range `[1, N]`
`--loss_function logistic` is for binary classification with labels in {-1, 1}

Would be nice to have better error handling here, however doing a full-range consistency check among > 100 options VW supports may lead to a pretty big bloat.

The "cannot specified more than once" is because the option has been already set (from the loaded model.  IOW: when testing there's no need to respecify the options that are already set in the model.  This check was put in place to prevent option contradictions between train and test.

**Comment by ma2rten** [comment]
Thanks for the quick response!

I got this extact combination of commanline args from the fastml-blog (mentioned in the vw wiki). And I also saw it mentioned elsewhere online. It must have worked with a previous version of vw.

**Comment by ma2rten** [comment]
I don't want to abuse this as a support forum, but I have new issue:

    vw --oaa 121 -d train.vw -f model
    vw -i model -t -d test.vw -r raw_predictions.txt

generates an empty raw_predictions.txt file

**Comment by arielf** [comment]
Hi,

This might be a bug.  Could you open a separate issue and include a minimal input so it can be reproduced by others? Thanks!

**Comment by JohnLangford** [comment]
Thanks Maarten.

--loss_function logistic and --oaa are supposed to be compositional 
because oaa is a reduction.  The problem here was that the base label 
was not properly chosen when -t was on.  This is fixed now.

-John

**Comment by JohnLangford** [comment]
This was a bug as well, essentially due to parsing order.   Should be 
fixed now.

-John

**Comment by ma2rten** [comment]
Thanks you, John and Ariel. 

I don't think there are many open source (or commercial) projects that would have fixed a issue so quickly.
