### ISSUE TITLE
large feature values yield empty model

### ISSUE THREAD

**Issue by laurajacob** [JohnLangford/vowpal_wabbit#537]
Hi,

if I pass vw a very large feature value, it will yield an empty model: 

echo "-1.0 | /foo/BAR:50233425598702010000.00" | ./vw --loss_function logistic -b 22 -f /mnt2/tmp/vwtest0.model --readable_model vwreadable.model; ls -l vwtest0.model vwreadable.model

These models are empty with no features. I believe this is because in example.h, on line 74 the squared total sum of features is being stored in a float, and that value is never checked for overflow.

**Comment by arielf** [comment]
Thanks for the report.

I'm getting a (non-empty) model with NaN in the weights:

```
$ echo "-1.0 | /foo/BAR:50233425598702010000.00" | vw --loss_function logistic --readable_model z.rmodel

$ cat z.rmodel
Version 7.10.0
Min label:-50.000000
Max label:50.000000
bits:18
0 pairs:
0 triples:
lda:0
0 ngram:
0 skip:
options:
:0
116060:nan
228181:nan
```

`vw` will check (and warn) about NaNs in input in some cases but evidently not in all cases.  If I simply double the line above and use this input:
```
-1.0 | /foo/BAR:50233425598702010000.00
-1.0 | /foo/BAR:50233425598702010000.00
```
Then I do get one (rather than two) NaN warning:
```
NAN prediction in example 2, forcing 0.0
```
Between the two examples.  So there's a check for nan before output (after prediction) but not at the end of parseFloat.  This may be due to performance reasons since `parseFloat()` is in the innermost loop of the parsing thread.

It seems a tradition for `atof` like functions to avoid error checking (see e.g. `man atof` on Ubuntu: quote:  `The behavior is the same as strtod(nptr, NULL) except that atof() does not detect errors.`)

John what do you think?  Should we add a nan check at the end of parseFloat() too?

**Comment by JohnLangford** [comment]
I suspect that NaN is being generated in the update rule rather than in 
the parsing.  I'm not sure what to do about this one---adding a 
nan-check in the update rule itself seems undesirable computationally.

-John

**Comment by JohnLangford** [comment]
What I suspected was confirmed in another bug report.  I'm still not sure what to do about this.

**Comment by JohnLangford** [comment]
I added an exception to address this.
