### ISSUE TITLE
contextual bandit examples

### ISSUE THREAD

**Issue by mikerlynn** [JohnLangford/vowpal_wabbit#548]
Can someone help with the inputs on this example as it would related to online advertising?

action - the unique id of the event that occurred, like perhaps the id of the ad that was shown, possibly the an id representing the ad unit shown, and where.

cost is the cost observed for this action.  This guy here didn't understand it in this context either.

http://stats.stackexchange.com/questions/92271/cost-functions-for-contextual-bandits

probability  - this one doesn't make sense to me - would it be the odds that this action id occured?   If you a million ads and you're selecting one randomly - would the probability be 0.000001.  What if it wasn't random selection?  What if you selected 10 ads to show them in this period?  would it be .1?

**Comment by MLWave** [comment]
See: https://github.com/JohnLangford/vowpal_wabbit/wiki/Contextual-Bandit-Example

_The data is specified as a set of tuples (x,a,c,p) where x are the current features/context for the decision, a is the chosen action by the exploration policy for the context x, c is the observed cost for action a **in context x**, and p is the probability the exploration policy choose this action in context x._

Displaying an ad has a cost which you set in your CB learning policy. Displaying ads on better screen real-estate (context: top banner vs. side banner) can carry a higher cost. A click on an ad reduces its cost.

The --cb part of Vowpal Wabbit is for optimizing already learned contextual bandits. It does not handle the exploration part. Your contextual bandit should already be exploiting certain ads with a higher probability, because during exploration it found more clicks on these ads.

For questions and help there is also the https://groups.yahoo.com/neo/groups/vowpal_wabbit/info

**Comment by JohnLangford** [comment]
Note that we have factored out an exploration library to make doing 
exploration easier.

Also note that there are some test cases related to contextual bandits 
which shows explicitly how to deal with formatting issues.

-John

**Comment by JohnLangford** [comment]
Closing, under the assumption this is handled.
