### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by djstrong** [JohnLangford/vowpal_wabbit#687]
It would be great to see full usage documentation, especially for search tasks.

E.g. my last problem with dep_parser was "num_label" argument nowhere mentioned.

**Comment by arielf** [comment]
To clarify.  Is what you're looking for, missing after the (admittedly not obvious) invocation:

```
vw --help --search 1
```
?

If not: we may need to better document how to get help on the subsystems options (like search)

If yes: it should be added to `vowpalwabbit/search.cc` by someone who understands this missing option name and effects.

So if yes: can you add and send a pull-request?

Otherwise, @hal3 can you help here?

**Comment by hal3** [comment]
+CC Kai-Wei who wrote this :)

**Comment by KaiWeiChang** [comment]
Okay, I'll add the usages documentation of search tasks.

**Comment by djstrong** [comment]
Partially yes. I was looking at command line in Wiki - my mistake. The other thing is e.g. input data format for dep_parser - I found it in test.

**Comment by KaiWeiChang** [comment]
The scripts for generating dep_parser data can be found in the demo/dependencyparsing. 
But, in general, we need a better documentation of the search system and these demo tasks.

**Comment by JohnLangford** [comment]
What's the status of this?  @KaiWeiChang  you've upgraded the dep parser code quite a bit.  is it ready for another pull request?

**Comment by KaiWeiChang** [comment]
Yes. I can wrap it up and send a pull request.
Regarding the better data input format, Hal mentioned that there is a way
to use strings as labels. I'll look into it.

**Comment by KaiWeiChang** [comment]
Quick question:

I remember last time in the meeting, Hal mentioned that there is a way to
use strings instead of integers as labels.
Is it easy to integrate this with l2s applications? Do you have an example
code?
I would like to upgrade the label system in dependency parser, but I could
not find out how to use it after a quick search.

Best,
Kai-Wei

**Comment by KaiWeiChang** [comment]
take a look at test 90 in RunTests. it's only for csoaa but should be 
close enough. lmk if you can't figure it out.

**Comment by JohnLangford** [comment]
Closing, I think this is dealt with.
