### ISSUE TITLE
Dep_parser segfault

### ISSUE THREAD

**Issue by djstrong** [JohnLangford/vowpal_wabbit#689]
I trained model successfully on data from tests:
```
$ vw -k -c -d wsj_small.dparser.vw --passes 6 --search_task dep_parser --search 2 --search_alpha 1e-4 --search_rollout ref --holdout_off -b 27 -f wsj.model
```
However testing causes segmentation fault:
```
$ vw -t -d wsj_small.dparser.vw -i wsj.model 
only testing
Num weight bits = 27
learning rate = 10
initial_t = 1
power_t = 0.5
using no cache
Reading datafile = wsj_small.dparser.vw
num sources = 1
Segmentation fault (core dumped)
```
Strace tail is:
```
open("wsj_small.dparser.vw", O_RDONLY)  = 3
write(2, "num sources = ", 14num sources = )          = 14
write(2, "1", 11)                        = 1
write(2, "\n", 1
)                       = 1
mmap(NULL, 4517888, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f76c0510000
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f76bfd0f000
mprotect(0x7f76bfd0f000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f76c050ef70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f76c050f9d0, tls=0x7f76c050f700, child_tidptr=0x7f76c050f9d0) = 11775
futex(0x1736a2c, FUTEX_WAIT_PRIVATE, 1, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1736a00, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x1736a00, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x1736a00, FUTEX_WAKE_PRIVATE, 1) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffffffffffffd0} ---
+++ killed by SIGSEGV (core dumped) +++
```
I compiled vw on Ubuntu with default options.

**Comment by JohnLangford** [comment]
I'm not sure what the issue is, but perhaps others know?

-John

**Comment by JohnLangford** [comment]
I think it crashing in my module. At least on my PC.

Btw, it seems that this operator is incorrect:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/global_data.h#L89

bool operator<=(version_struct v) { return !(*this < v); }

should be

bool operator<=(version_struct v) { return !(*this > v); }
I'm using it  in this line
https://github.com/JohnLangford/vowpal_wabbit/blob/afdf8426c3ebe55e77727b2cb2c002008c958a74/vowpalwabbit/parse_regressor.cc#L204
after recent commit.

Pls anyone feel free to fix it.

But the problem is still reproducible. I'll take a closer look a bit later.


2015-06-16 16:52 GMT+04:00 John Langford jl@hunch.net [vowpal_wabbit] <
vowpal_wabbit@yahoogroups.com>:

**Comment by JohnLangford** [comment]
Yep, it's in my code. Sorry for that.

The line
 all.interactions.erase();
should be added before this one:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/search_dep_parser.cc#L58

Otherwise interactions.end wont be reseted and new interactions will be
pushed after already deleted array. And in GD::foreach_features it starts
with deleted interactions first and this lead to crash.

I can't create PRs right now. Could someone do a favor to me?


2015-06-16 20:31 GMT+04:00 Alexander Trufanov <alexander.trufanov@yahoo.com>
:

**Comment by djstrong** [comment]
Thank you! It is working now. I created PR.
