### ISSUE TITLE
creating a VW shared library (libvw.so and liballreduce.so)

### ISSUE THREAD

**Issue by SelimRaboudi** [JohnLangford/vowpal_wabbit#748]
I am trying to create shared libraries for vowpal wabbit, as I am building a program that needs to link dynamically to VW.

Here is my attempt on the Makefile (for the latest version of VW):
```
liballreduce.so: allreduce.o
        gcc -shared -fPIC -o $@ $<

libvw.so: $(filter-out vw.o,$(vw_OBJECTS))
        gcc -shared -fPIC -o $@ $+ 
```

This gets build, but yields error when linked to my C++ code. A typical one:
```
symbol lookup error: ./exec: undefined symbol: _ZN2VW9get_labelEP7example
```

What am I doing wrong ?

**Comment by sharatsc** [comment]
Can you try $(CXX) instead of hardcoding gcc in there? Name munging is complier(and version) specific.

**Comment by arielf** [comment]
Thanks Sharat,

@slymore If it helps: there's tool called `c++filt` which demangles symbols:

```
$ c++filt  _ZN2VW9get_labelEP7example
VW::get_label(example*)
```
Undefined symbol is commonly caused by one of two things:
1) As Sharat explained: the library and your program were compiled by two different/incompatible compilers do the mangling isn't compatible
2)  Dynamic linking isn't finding the library (library is in non standard location OR missing -L <directory-where-library-can-be-found> during link time)

**Comment by JohnLangford** [comment]
Is this solved?

Incidentally, I believe the autoconf build creates a shared library.

-John

**Comment by JohnLangford** [comment]
Closing for lack of response.
