### ISSUE TITLE
predictions from quantile regression

### ISSUE THREAD

**Issue by zachmayer** [JohnLangford/vowpal_wabbit#838]
Lets say I run a simple quantile regression in VW:
```{bash}
echo '1000 |a a:1 \n10000 |a a:1\n100000 |a a:1' > vw.txt
vw vw.txt --loss_function quantile --quantile_tau 0.5 -f model.vw
vw vw.txt -t -i model.vw -p preds.txt
cat preds.txt
```

The result is:
```{bash}
1.614986
1.614986
1.614986
```

What does `1.614` mean in the context of my training examples, which are `1000, 10000, 100000`?  Is there way to transform them to be on the same scale as my original data, e.g. something like:
```{bash}
10000
10000
10000
```
Where 10000 is the median of the original dataset?

**Comment by arielf** [comment]
The command:
```
echo '1000 |a a:1 \n10000 |a a:1\n100000 |a a:1' > vw.txt
```

Creates a one line file in my env.

Trying to answer the question: `vw` is a not a batch learner.  You need to give it a chance to converge.  A 3 line example like the above with one pass, isn't sufficient.  It converges very slowly because the input features have nothing to do with the (highly varying) target.

You can get it to converge on this example, to near the median 10000 if you give it a chance by adding:

1) More passes
2) --holdout_off
3) higher learning rate

e.g. with this command:
```
vw vw.txt --loss_function quantile --quantile_tau 0.5 -f model.vw -P 10 -c --passes 100 --holdout_off -l 1000
```

I can get it to converge to 10000 after seeing ~100 examples.  And if I increase the learning rate to `-l 1000` I get the expected median 10000 prediction after 30 examples (10 passes).

HTH

**Comment by zachmayer** [comment]
Right, of course.

Thanks
