### ISSUE TITLE
vw-varinfo does not work with -oaa

### ISSUE THREAD

**Issue by udibr** [JohnLangford/vowpal_wabbit#855]
You get an error message that oaa can not be defined twice (i.e. it is passed from a first call to vw to a second call through the model)

As a patch I commented line 500 of vw-varinfo

        # $vw_mcargs = $&;

hopefully this is the right solution but I am not knowldgeable enough in perl or in what the script does

**Comment by arielf** [comment]
Thanks Udi,

Yes, this minimalistic change should fix it.

When I wrote this back in 2012, `vw` wasn't checking and giving that error.

It would be even nicer to get rid of all the logic involving multi-class arguments in `audit_features()`, not just this specific line.

Also there were many options added to `vw` since and many wouldn't be supported.  It is on my todo list to rewrite this utility to be both faster and more adaptive to future changes.

**Comment by JohnLangford** [comment]
I did this edit for now.

The issue of scripts not updating with the core codebase is a persistent one.  I'm not sure what we can do about that.
