### ISSUE TITLE
L2 regularization shrinks the intercept as well.

### ISSUE THREAD

**Issue by sharatsc** [JohnLangford/vowpal_wabbit#919]
This causes some bias to be introduced on large volume datasets since intercept cannot capture the overall bias. As far as I know, there isn't an option to exempt intercept from regularization.

**Comment by JohnLangford** [comment]
We do have an implementation of separating updates on constant and non-constant features in FTRL, which is not pushed back yet since it's an unclean and less generalizable solution. (https://github.com/sinaad/vowpal_wabbit/commit/01cea80c330c31c456357f14b7527dc318af4d36).

And I think a better way to handle this is to move the bias term out of feature/example. It's a global parameter and we do not need to set it up in the feature array.

Thanks,
-Gang

________________________________
发件人: vowpal_wabbit@yahoogroups.com [vowpal_wabbit@yahoogroups.com]
发送时间: 2016年1月28日 8:43
收件人: JohnLangford/vowpal_wabbit; vowpal_wabbit@yahoogroups.com
主题: Re: [vowpal_wabbit] L2 regularization shrinks the intercept as well. (#919)



This is correct. There is a hack though---you could make your own
constant feature which has a large value. Since regularization is not
unit invariant the bias can be made negligible.

I don't see a good way to do something else, computationally. Do you?

Having a test on every feature update which triggers at most once per
example seems... kind of unclean. Having a different update rule for
the constant feature seems worse.

-John

On 01/25/2016 02:53 PM, Sharat Chikkerur wrote:
>
> This causes some bias to be introduced on large volume datasets since
> intercept cannot capture the overall bias. As far as I know, there
> isn't an option to exempt intercept from regularization.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnLangford/vowpal_wabbit/issues/919>.
>


__._,_.___
________________________________
Posted by: John Langford <jl@hunch.net>
________________________________
Reply via web post<https://groups.yahoo.com/neo/groups/vowpal_wabbit/conversations/messages/5764;_ylc=X3oDMTJxajMzOGEwBF9TAzk3MzU5NzE0BGdycElkAzczNzEzNTMzBGdycHNwSWQDMTcwNzI4MTk0MgRtc2dJZAM1NzY0BHNlYwNmdHIEc2xrA3JwbHkEc3RpbWUDMTQ1Mzk0MTg0MQ--?act=reply&messageNum=5764>   •       Reply to sender <mailto:jl@hunch.net?subject=Re%3A%20%5Bvowpal_wabbit%5D%20L2%20regularization%20shrinks%20the%20intercept%20as%20well%2E%20%28%23919%29>       •       Reply to group <mailto:vowpal_wabbit@yahoogroups.com?subject=Re%3A%20%5Bvowpal_wabbit%5D%20L2%20regularization%20shrinks%20the%20intercept%20as%20well%2E%20%28%23919%29>       •       Start a New Topic<https://groups.yahoo.com/neo/groups/vowpal_wabbit/conversations/newtopic;_ylc=X3oDMTJmZDNjaGI2BF9TAzk3MzU5NzE0BGdycElkAzczNzEzNTMzBGdycHNwSWQDMTcwNzI4MTk0MgRzZWMDZnRyBHNsawNudHBjBHN0aW1lAzE0NTM5NDE4NDE->   •       Messages in this topic<https://groups.yahoo.com/neo/groups/vowpal_wabbit/conversations/topics/5764;_ylc=X3oDMTM1cGMxbHAwBF9TAzk3MzU5NzE0BGdycElkAzczNzEzNTMzBGdycHNwSWQDMTcwNzI4MTk0MgRtc2dJZAM1NzY0BHNlYwNmdHIEc2xrA3Z0cGMEc3RpbWUDMTQ1Mzk0MTg0MQR0cGNJZAM1NzY0> (1)
Visit Your Group<https://groups.yahoo.com/neo/groups/vowpal_wabbit/info;_ylc=X3oDMTJmdmZtbnM1BF9TAzk3MzU5NzE0BGdycElkAzczNzEzNTMzBGdycHNwSWQDMTcwNzI4MTk0MgRzZWMDdnRsBHNsawN2Z2hwBHN0aW1lAzE0NTM5NDE4NDE->

  *   New Members<https://groups.yahoo.com/neo/groups/vowpal_wabbit/members/all;_ylc=X3oDMTJnZ3Fic3AxBF9TAzk3MzU5NzE0BGdycElkAzczNzEzNTMzBGdycHNwSWQDMTcwNzI4MTk0MgRzZWMDdnRsBHNsawN2bWJycwRzdGltZQMxNDUzOTQxODQx> 1

[Yahoo! Groups]<https://groups.yahoo.com/neo;_ylc=X3oDMTJlbGozaWEzBF9TAzk3MzU5NzE0BGdycElkAzczNzEzNTMzBGdycHNwSWQDMTcwNzI4MTk0MgRzZWMDZnRyBHNsawNnZnAEc3RpbWUDMTQ1Mzk0MTg0MQ-->
• Privacy<https://info.yahoo.com/privacy/us/yahoo/groups/details.html> • Unsubscribe<mailto:vowpal_wabbit-unsubscribe@yahoogroups.com?subject=Unsubscribe> • Terms of Use<https://info.yahoo.com/legal/us/yahoo/utos/terms/>

.


__,_._,___

**Comment by JohnLangford** [comment]
Filtering on the namespace like that eliminates some of the awkwardness 
compared to what I was imagining.

But this seems like failing of the learning algorithm.  Why should we 
treat the bias feature as 'special'?

-John

**Comment by sharatsc** [comment]
I like the namespace exclusion idea. As for why we need to exclude bias from regularization. A large value of regularization can produced biased predictions. In SGD, since we apply regularization on every round and at every pass, it can be effectively large compared to the overall log-loss term. In contrast for BFGS, regularization is applied at every pass and hence behaves reasonably.

**Comment by JohnLangford** [comment]
Does this update rule:

http://arxiv.org/abs/1602.02202

address the problem?

-John

**Comment by JohnLangford** [comment]
@sharatsc have you considered making a patch for this?

**Comment by JohnLangford** [comment]
Closing this for now.  A patch is welcome.
