### ISSUE TITLE
scan-build static analysis multiple bugs

### ISSUE THREAD

**Issue by arielf** [JohnLangford/vowpal_wabbit#935]
I ran clang's static analyzer (`scan-build`) on latest master and it uncovered several issues that look like bona-fide bugs not covered by the test suite.

Here's a link to the report:

[scan-buid report on vowpal wabbit 2016-02-08](http://yendor.com/scan-build-2016-02-08/)

Summary of issues uncovered:

   ```
    Bug Group     Bug Type                                 File             Line
    Logic error   Branch condition evaluates to garbage    kernel_svm.cc     579
    Dead store    Dead assignment                          multiclass.cc      50
    Dead store    Dead increment                           gd.cc             590
    Dead store    Dead initialization                      search.cc         885
    Dead store    Dead initialization                      search.cc         936
    Logic error   Dereference of null pointer              cb_algs.cc         63
```

@trufanov-nok may be up your alley?

**Comment by arielf** [comment]
Went through these.  All the 'Dead ...' are simply unused values so not really bugs but questionable assignments.

The last one in `cb_algs.cc` I'm not sure because of C++ opaqueness.

I'm fixing `kernel_svm.cc` which is a bug (potential use of uninitialized value).

**Comment by eisber** [comment]
I had a look and I’m not getting it.

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/cb_algs.cc#L63

does call begin()  and end() https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/v_array.h#L35 and https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/v_array.h#L36

ld is by ref, so that can’t be null. And ld.cost is not a pointer either.
ld.cost is initializes through the regular calloc.

According to http://en.cppreference.com/w/cpp/language/range-for the loop is transformed into

auto && __range = range_expression ;
for (auto __begin = begin_expr,
__end = end_expr;
__begin != __end; ++__begin) {
range_declaration = *__begin;
loop_statement
}

begin_expr being ld.cost.begin() and end_expr being ld.cost.end()

Markus

**Comment by arielf** [comment]
Hi Markus, 
I don't get it either.  It is possible that this is a bug in the clang static analyzer.  OTOH the ones I do understand all are real, so I was hoping someone with higher C++ fu will be able to figure this out.   I fixed one additional uninitialized `fec` pointer in `kernel_svm.cc` I could find. The other one I saw (line 255: `stringstream msg;`) is a constructor initialized at declaration, so shouldn't be an issue.   

There's also some legacy dead code in this file (which will be optimized away by the optimizer):
```
          int randi = 1;//rand()%2;
          if(randi) {
             ... always executed ...
          } else {
             ... never executed ...
          }
```
I left that alone.
Whoever understands the history of this (@alekh Alekh Agarwal) may be the best person to remove.

**Comment by alekh** [comment]
Ah, I see. The correct code got commented probably at some debugging point.
randi should be rand()%2 and not 1 :) Then the following if is not
meaningless.

Alekh

**Comment by JohnLangford** [comment]
I am fixing this.

-John

**Comment by JohnLangford** [comment]
All of these are fixed except for the last one.  I don't follow it, and 
neither does Markus.  Does anyone else?

-John

**Comment by JohnLangford** [comment]
I believe the line 63 issue is a false positive at this point.  Closing for now.
