### ISSUE TITLE
multiple errors in the configure and makefile process on Mac

### ISSUE THREAD

**Issue by kamal94** [JohnLangford/vowpal_wabbit#970]
**1)** The ```--without-zlib ``` does not work. I still get the lines
```
ZLIB_CPPFLAGS = -I/include
ZLIB_LDFLAGS = -L/lib -lz
```
in the make file.

**2)** The ```-L/lib``` include flag keeps showing warnings when compiling
(example:

```libtool: link: clang++ -I/usr/local/include -I/include -D_THREAD_SAFE -stdlib=libc++ -std=gnu++11 -o .libs/ezexample_predict ezexample_predict.o -Wl,-bind_at_load  -L/usr/local/lib -L/lib ../vowpalwabbit/.libs/libvw.dylib /Users/Kamal/Repositories/vo5/vowpalwabbit/.libs/liballreduce.dylib ../vowpalwabbit/.libs/liballreduce.dylib -lboost_program_options-mt -lz -lpthread
ld: warning: directory not found for option '-L/lib'```

and more drastically sometimes causes the compilation to fail

**3)**
when installing only python with ```make python``` (after configuring with ```./configure --enable-libc++ CXX=clang++ --without-zlib```), I get the following error after long successful compilations:

```
libtool: link: clang++ -I/usr/local/include -I/include -D_THREAD_SAFE -stdlib=libc++ -std=gnu++11 -o .libs/ezexample_predict ezexample_predict.o -Wl,-bind_at_load  -L/usr/local/lib -L/lib ../vowpalwabbit/.libs/libvw.dylib /Users/Kamal/Repositories/vo5/vowpalwabbit/.libs/liballreduce.dylib ../vowpalwabbit/.libs/liballreduce.dylib -lboost_program_options-mt -lz -lpthread
ld: warning: directory not found for option '-L/lib'
 .././install-sh -c -d '/usr/local/bin'
  /bin/sh ../libtool   --mode=install /usr/bin/install -c library_example ezexample_train ezexample_predict '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/library_example /usr/local/bin/library_example
libtool: install: /usr/bin/install -c .libs/ezexample_train /usr/local/bin/ezexample_train
libtool: install: /usr/bin/install -c .libs/ezexample_predict /usr/local/bin/ezexample_predict
make[2]: Nothing to be done for `install-data-am'.
make[1]: *** No rule to make target `noinst_HEADERS', needed by `all-am'.  Stop.
make: *** [install-recursive] Error 1
```

**Comment by arielf** [comment]
This is because your _Makefile.am_ has been broken with the wrong fix
(See comment on [https://github.com/JohnLangford/vowpal_wabbit/pull/968](https://github.com/JohnLangford/vowpal_wabbit/pull/968))

**Comment by kamal94** [comment]
You are correct on number **3**, this was caused by #968 and a fix was suggested by #971 but the problems in **1** and **2** still remain. It seems that the ```--without-zlib``` option is not working properly.

**Comment by arielf** [comment]
About 2) the warning is harmless.  We need to support multiple platforms, so that's a small price to pay.  If you actually get an errror, please post it.

Regarding 1) this looks like a autogen/autoconf/configure issue.   We always recommend trying the `Makefile` that is in the tree before venturing into the autogen/autoconf/configure great unknown.  It is much simpler and probably much easier to fix, even for Mac OS-X where some people use homebrew, some others use fink and who knows what else.

**Comment by arielf** [comment]
A general comment on the OS-X pains:
Mac users don't have a standard env like all Ubuntu/Debian users normally have. They use different envs: dockerized, virtualbox, anaconda, virtualenvs... Guessing where your python is to install it so that `import pyvw` always works for everyone is hard.  Any patches from Mac OS-X users, which work for more people are very welcome.

Regarding link issues of `vw` vs `libboost`: that's a general C++ issue: in order for boost and vw to be binary compatible, they must be built with the same source version (and often the same toolchain: gcc+version, or clang+version).  Mixing different versions often leads to unresolved symbols.  In Ubuntu we pre-install libboost-dev (rather than just libboost) so that `vw` builds against compatible boost headers/templates, not just the `*.so`s.

**Comment by JohnLangford** [comment]
Closing for now.  Patches to make things work better on a mac are welcome.
